"""add relations for job_postings

Revision ID: 39abc949f756
Revises: 6bd25e745c8e
Create Date: 2026-08-22 16:32:39.238245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39abc949f756'
down_revision: Union[str, Sequence[str], None] = '6bd25e745c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.add_column('job_postings', sa.Column('province_id', sa.Integer(), nullable=False))
    op.add_column('job_postings', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job_postings', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'provinces', ['province_id'], ['id'])
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_github_id_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_google_id_key'), 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=True)
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=False)
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_unique_constraint(op.f('user_google_id_key'), 'user', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_github_id_key'), 'user', ['github_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'city_id')
    op.drop_column('job_postings', 'province_id')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
