"""add models

Revision ID: 3b8adc2c9521
Revises:
Create Date: 2026-08-18 16:26:10.546056

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b8adc2c9521"
down_revision: str | Sequence[str] | None = "1a2b3c4d5e6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "rate_limits", ["id"])
    op.create_unique_constraint(None, "tiers", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "tiers", type_="unique")
    op.drop_constraint(None, "rate_limits", type_="unique")
    # ### end Alembic commands ###
