"""add job_categories table

Revision ID: 473ab00f421d
Revises: 825f63526e94
Create Date: 2026-08-22 12:06:23.011471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473ab00f421d'
down_revision: Union[str, Sequence[str], None] = '825f63526e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job_postings', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('job_postings', sa.Column('job_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job_postings', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'job_categories', ['job_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'job_category_id')
    op.drop_column('job_postings', 'created_by_id')
    op.drop_table('job_categories')
    # ### end Alembic commands ###
