"""add skills table

Revision ID: 7cc859308b61
Revises: 827e640343d7
Create Date: 2026-08-24 17:33:09.676959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc859308b61'
down_revision: Union[str, Sequence[str], None] = '827e640343d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['applicant_profile_id'], ['applicant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_profile_id', 'title')
    )
    op.alter_column('applicant_profiles', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('applicant_profiles', 'about',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicant_profiles', 'about',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('applicant_profiles', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('applicant_skills')
    # ### end Alembic commands ###
