"""add job_postings table

Revision ID: 825f63526e94
Revises: c7a4e9d1f263
Create Date: 2026-08-20 13:03:30.652852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825f63526e94'
down_revision: Union[str, Sequence[str], None] = 'c7a4e9d1f263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('company_overview', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'internship', name='employmenttype'), nullable=False),
    sa.Column('work_mode', sa.Enum('onsite', 'remote', 'hybrid', name='workmode'), nullable=False),
    sa.Column('minimum_salary', sa.BigInteger(), nullable=True),
    sa.Column('is_latin_text', sa.Boolean(), nullable=False),
    sa.Column('work_experience', sa.Enum('not_important', 'less_than_3_years', 'three_to_six_years', 'more_than_6_years', name='relevantworkexperience'), nullable=False),
    sa.Column('minimum_education', sa.Enum('not_important', 'diploma', 'associate', 'bachelor', 'master', 'doctorate', name='minimumeducationlevel'), nullable=False),
    sa.Column('gender', sa.Enum('not_important', 'male', 'female', name='gender'), nullable=False),
    sa.Column('military_status', sa.Enum('not_important', 'completed', 'educational_exemption', 'permanent_exemption', name='militaryservicestatus'), nullable=False),
    sa.Column('post_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings')
    # ### end Alembic commands ###
