"""add general informations to applicant_profile

Revision ID: 827e640343d7
Revises: d21e6f904b7a
Create Date: 2026-08-24 17:11:05.438755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827e640343d7'
down_revision: Union[str, Sequence[str], None] = 'd21e6f904b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_profiles', sa.Column('specialization', sa.String(length=100), nullable=True))
    op.add_column('applicant_profiles', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('applicant_profiles', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('applicant_profiles', sa.Column('military_status', sa.String(length=50), nullable=True))
    op.add_column('applicant_profiles', sa.Column('martial_status', sa.String(length=20), nullable=True))
    op.add_column('applicant_profiles', sa.Column('province', sa.String(length=50), nullable=True))
    op.add_column('applicant_profiles', sa.Column('address', sa.String(), nullable=True))
    op.add_column('applicant_profiles', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicant_profiles', 'about')
    op.drop_column('applicant_profiles', 'address')
    op.drop_column('applicant_profiles', 'province')
    op.drop_column('applicant_profiles', 'martial_status')
    op.drop_column('applicant_profiles', 'military_status')
    op.drop_column('applicant_profiles', 'gender')
    op.drop_column('applicant_profiles', 'birth_year')
    op.drop_column('applicant_profiles', 'specialization')
    # ### end Alembic commands ###
