"""initial migration

Revision ID: a841adf9060f
Revises: 
Create Date: 2026-08-25 13:11:13.093208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a841adf9060f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications_folder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_ranges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rate_limits_tier_id'), 'rate_limits', ['tier_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('google_id', sa.String(length=50), nullable=True),
    sa.Column('github_id', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('oauth_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("user_type IN ('applicant', 'employer')", name='ck_user_user_type'),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=True)
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    op.create_index(op.f('ix_user_tier_id'), 'user', ['tier_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_limits', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_expires_at', 'api_keys', ['expires_at'], unique=False)
    op.create_index('idx_api_keys_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_api_keys_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('persian_name', sa.String(length=120), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('personnel_count', sa.Enum('2_10', '11_50', '51_200', '201_500', '501_1000', '1000_PLUS', name='employeecount'), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['company_activities.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('company_logo', 'user_avatar', 'resume', 'attachment')", name='ck_media_category'),
    sa.CheckConstraint('size_bytes > 0', name='ck_media_size_bytes_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_category'), 'media', ['category'], unique=False)
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_storage_key'), 'media', ['storage_key'], unique=True)
    op.create_table('applicant_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('attached_resume_id', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('military_status', sa.String(length=50), nullable=True),
    sa.Column('martial_status', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['attached_resume_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id'),
    sa.UniqueConstraint('attached_resume_id')
    )
    op.create_table('company_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_category_id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('company_overview', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'internship', name='employmenttype'), nullable=False),
    sa.Column('work_mode', sa.Enum('onsite', 'remote', 'hybrid', name='workmode'), nullable=False),
    sa.Column('salary_range_id', sa.Integer(), nullable=False),
    sa.Column('is_latin_text', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'needs_review', 'draft', 'closed', 'archived', name='jobpostingstatus'), server_default='needs_review', nullable=False),
    sa.Column('work_experience', sa.Enum('not_important', 'less_than_3_years', 'three_to_six_years', 'more_than_6_years', name='relevantworkexperience'), nullable=False),
    sa.Column('minimum_education', sa.Enum('not_important', 'diploma', 'associate', 'bachelor', 'master', 'doctorate', name='minimumeducationlevel'), nullable=False),
    sa.Column('gender', sa.Enum('not_important', 'male', 'female', name='gender'), nullable=False),
    sa.Column('military_status', sa.Enum('not_important', 'completed', 'educational_exemption', 'permanent_exemption', name='militaryservicestatus'), nullable=False),
    sa.Column('post_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_category_id'], ['job_categories.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.ForeignKeyConstraint(['salary_range_id'], ['salary_ranges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.Enum('CONVERSATIONS', 'CREDITS', 'AI_USAGE', 'USER_PROFILE', 'ANALYTICS', 'ADMIN', 'BILLING', 'API_KEYS', 'WILDCARD', name='keypermissionresource'), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'DELETE', 'CREATE', 'UPDATE', 'LIST', 'ADMIN', 'WILDCARD', name='keypermissionaction'), nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_permissions_key_resource', 'key_permissions', ['api_key_id', 'resource', 'action'], unique=True)
    op.create_index('idx_key_permissions_resource_action', 'key_permissions', ['resource', 'action'], unique=False)
    op.create_index(op.f('ix_key_permissions_action'), 'key_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_key_permissions_api_key_id'), 'key_permissions', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_key_permissions_resource'), 'key_permissions', ['resource'], unique=False)
    op.create_table('key_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_microcents', sa.BigInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('usage_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_usage_endpoint', 'key_usage', ['endpoint'], unique=False)
    op.create_index('idx_key_usage_key_created', 'key_usage', ['api_key_id', 'created_at'], unique=False)
    op.create_index('idx_key_usage_status', 'key_usage', ['status_code'], unique=False)
    op.create_index('idx_key_usage_user_created', 'key_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_key_usage_api_key_id'), 'key_usage', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_key_usage_endpoint'), 'key_usage', ['endpoint'], unique=False)
    op.create_index(op.f('ix_key_usage_status_code'), 'key_usage', ['status_code'], unique=False)
    op.create_index(op.f('ix_key_usage_user_id'), 'key_usage', ['user_id'], unique=False)
    op.create_table('applicant_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['applicant_profile_id'], ['applicant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_profile_id', 'title')
    )
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=False),
    sa.Column('education_level', sa.Enum('DIPLOMA', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'PHD', 'OTHER', name='educationlevel'), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_currently_studying', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('(is_currently_studying = true AND end_year IS NULL) OR (is_currently_studying = false AND end_year IS NOT NULL)', name='ck_education_current_status'),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['job_applications_folder.id'], ),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('minimum_salary_range_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['minimum_salary_range_id'], ['salary_ranges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id'),
    sa.UniqueConstraint('profile_id', name='uq_job_preferences_profile_id')
    )
    op.create_table('language_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'PROFESSIONAL', 'NATIVE', name='languagelevel'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=200), nullable=False),
    sa.Column('workplace_name', sa.String(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('experience_description', sa.Text(), nullable=True),
    sa.CheckConstraint('(is_current = true AND end_month IS NULL AND end_year IS NULL) OR (is_current = false AND end_month IS NOT NULL AND end_year IS NOT NULL) OR (is_current IS NULL)', name='ck_work_experience_end_date_consistency'),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_preference_benefits',
    sa.Column('job_preference_id', sa.Integer(), nullable=False),
    sa.Column('benefit', sa.Enum('promotion_opportunity', 'insurance', 'training_courses', 'commuting_service', 'company_meal', 'flexible_working_hours', name='preferred_job_benefit'), nullable=False),
    sa.ForeignKeyConstraint(['job_preference_id'], ['job_preferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_preference_id', 'benefit')
    )
    op.create_table('job_preference_employment_types',
    sa.Column('job_preference_id', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'remote', 'internship', name='preferred_employment_type'), nullable=False),
    sa.ForeignKeyConstraint(['job_preference_id'], ['job_preferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_preference_id', 'employment_type')
    )
    op.create_table('job_preference_job_categories',
    sa.Column('job_preference_id', sa.Integer(), nullable=False),
    sa.Column('job_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_category_id'], ['job_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_preference_id'], ['job_preferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_preference_id', 'job_category_id')
    )
    op.create_table('job_preference_provinces',
    sa.Column('job_preference_id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_preference_id'], ['job_preferences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_preference_id', 'province_id')
    )
    op.create_table('job_preference_seniority_levels',
    sa.Column('job_preference_id', sa.Integer(), nullable=False),
    sa.Column('seniority_level', sa.Enum('entry_level', 'specialist', 'manager', 'senior_manager', name='preferred_seniority_level'), nullable=False),
    sa.ForeignKeyConstraint(['job_preference_id'], ['job_preferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_preference_id', 'seniority_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_preference_seniority_levels')
    op.drop_table('job_preference_provinces')
    op.drop_table('job_preference_job_categories')
    op.drop_table('job_preference_employment_types')
    op.drop_table('job_preference_benefits')
    op.drop_table('work_experiences')
    op.drop_table('language_skills')
    op.drop_table('job_preferences')
    op.drop_table('job_applications')
    op.drop_table('educations')
    op.drop_table('applicant_skills')
    op.drop_index(op.f('ix_key_usage_user_id'), table_name='key_usage')
    op.drop_index(op.f('ix_key_usage_status_code'), table_name='key_usage')
    op.drop_index(op.f('ix_key_usage_endpoint'), table_name='key_usage')
    op.drop_index(op.f('ix_key_usage_api_key_id'), table_name='key_usage')
    op.drop_index('idx_key_usage_user_created', table_name='key_usage')
    op.drop_index('idx_key_usage_status', table_name='key_usage')
    op.drop_index('idx_key_usage_key_created', table_name='key_usage')
    op.drop_index('idx_key_usage_endpoint', table_name='key_usage')
    op.drop_table('key_usage')
    op.drop_index(op.f('ix_key_permissions_resource'), table_name='key_permissions')
    op.drop_index(op.f('ix_key_permissions_api_key_id'), table_name='key_permissions')
    op.drop_index(op.f('ix_key_permissions_action'), table_name='key_permissions')
    op.drop_index('idx_key_permissions_resource_action', table_name='key_permissions')
    op.drop_index('idx_key_permissions_key_resource', table_name='key_permissions')
    op.drop_table('key_permissions')
    op.drop_table('job_postings')
    op.drop_table('company_memberships')
    op.drop_table('applicant_profiles')
    op.drop_index(op.f('ix_media_storage_key'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_index(op.f('ix_media_category'), table_name='media')
    op.drop_table('media')
    op.drop_table('companies')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index('idx_api_keys_user_active', table_name='api_keys')
    op.drop_index('idx_api_keys_prefix', table_name='api_keys')
    op.drop_index('idx_api_keys_expires_at', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_user_tier_id'), table_name='user')
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rate_limits_tier_id'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_table('cities')
    op.drop_table('tiers')
    op.drop_table('salary_ranges')
    op.drop_table('provinces')
    op.drop_table('job_categories')
    op.drop_table('job_applications_folder')
    op.drop_table('company_activities')
    # ### end Alembic commands ###
