"""add user_type to user

Revision ID: b2c3197eea6a
Revises: 20260815_01
Create Date: 2026-08-18 12:07:12.180411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3197eea6a'
down_revision: Union[str, Sequence[str], None] = '20260815_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rate_limits', ['id'])
    op.create_unique_constraint(None, 'tiers', ['id'])
    op.add_column('user', sa.Column('user_type', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_type')
    op.drop_constraint(None, 'tiers', type_='unique')
    op.drop_constraint(None, 'rate_limits', type_='unique')
    # ### end Alembic commands ###
