"""improve job_applications_folder table

Revision ID: be933347c767
Revises: b3e4d5f6a7c8
Create Date: 2026-08-25 11:40:52.357887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be933347c767'
down_revision: Union[str, Sequence[str], None] = 'b3e4d5f6a7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_applications', 'job_applications_folder', ['folder_id'], ['id'])
    op.create_unique_constraint(None, 'rate_limits', ['id'])
    op.create_unique_constraint(None, 'tiers', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tiers', type_='unique')
    op.drop_constraint(None, 'rate_limits', type_='unique')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_column('job_applications', 'folder_id')
    # ### end Alembic commands ###
