"""add code property to activities and categories

Revision ID: d2401d15a16a
Revises: be933347c767
Create Date: 2026-08-26 13:27:37.287681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2401d15a16a'
down_revision: Union[str, Sequence[str], None] = 'be933347c767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_activities', sa.Column('code', sa.String(), nullable=False))
    op.add_column('job_categories', sa.Column('code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_categories', 'code')
    op.drop_column('company_activities', 'code')
    # ### end Alembic commands ###
